owner: nimishgj
git-repo: helm-charts
charts-dir: charts
target-branch: gh-pages
package-path: .cr-release-packages
index-path: .cr-index
release-name-template: "{{ .Name }}-{{ .Version }}"
make-release-latest: false