# Global settings
global:
  # Container registry settings
  imageRegistry: ghcr.io
  imageRepository: nimishgj
  imageTag: latest
  imagePullPolicy: IfNotPresent

  # Common labels applied to all resources
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: hello-frameworks

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000

# Framework-specific configurations
goGin:
  enabled: true
  image:
    name: hello-gin
    port: 8080
    targetPort: 8080
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  healthCheck:
    path: /health
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
  service:
    type: ClusterIP
    port: 80

javaSpringboot:
  enabled: true
  image:
    name: hello-springboot
    port: 8080
    targetPort: 8080
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  healthCheck:
    path: /health
    port: 8080
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 5
  service:
    type: ClusterIP
    port: 80

nodejsExpress:
  enabled: true
  image:
    name: hello-express
    port: 8080
    targetPort: 8080
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  healthCheck:
    path: /health
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
  service:
    type: ClusterIP
    port: 80

pythonFastapi:
  enabled: true
  image:
    name: hello-fastapi
    port: 8080
    targetPort: 8080
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  healthCheck:
    path: /health
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
  service:
    type: ClusterIP
    port: 80

phpLaravel:
  enabled: true
  image:
    name: hello-laravel
    port: 80
    targetPort: 80
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  healthCheck:
    path: /api/health
    port: 80
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  service:
    type: ClusterIP
    port: 80

# Common configuration that can be overridden per framework
common:
  # Pod annotations
  podAnnotations: {}

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity rules
  affinity: {}

  # Service account
  serviceAccount:
    create: false
    name: ""